run:
  timeout: 5m
  issues-exit-code: 1
  tests: false
  skip-dirs:
    - parser

linters:
  enable:
    - errcheck
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused

linters-settings:
  lll:
    line-length: 120
    tab-length: 4
  misspell:
    locale: US

issues:
  exclude-files:
    - parser/sql\.go
  exclude-rules:
    - linters:
        - lll
      source: "//go:generate"
    - linters:
        - errcheck
      path: '_test\.go'
      source: 'Error|Fatal'
    - linters:
        - staticcheck
      source: "SA1019"  # Deprecated ioutil functions

severity:
  default-severity: error
